language: python
sudo: false
services:
- docker
os:
- linux
script:
- "./bin/dev-setup"
- "./bin/test"
- "./bin/install"
- mandelbrot-orbit -1.3 0.0 100 ./output/mandelbrot_orbit.png
deploy:
  provider: pypi
  username: __token__
  password:
    secure: DMp3v+y2TAxm80QFDQlsuSUwPOwIh+E8sarj5J0KEZGTTHIjr74OZmW/OhnN3kLbMcjYIcRmQzD432E5SpM7ENy+0+WzQtFIvt4/7Re6wwfSEInEczxBwelmyLob+vfN9YkP1yqVxxlza5nJnXzLrIonbrvt4Vci7A7EPtJLYwAFp96GsiLMqlcjvcOuIBtmjoyITMD2/Oos7TOXVQBcCxsCVbDGzGP4LbvGHnEAlCxJJsLIJAO/+7o27gjyZpf6pU7VPPZoO9cj9JHt4TmrxOs5+iHFJWH/Ztu3jsxSU4CGEaQ4lEyBXcNI5p/ihG1TVrLa8Bgm+KSb63Y4oeqKD1fwoQuBhLb+LPbqt2G+JCdLgvqDSIw8ozVHR6StZ9G+hFvwHDUxjGkSkoB8lq7UNIme0kR9bgps4CKUCzm40Gummw/rE13mvE1PrBtieQ1Cw0p7biJ/kh2RRPhN2/L75KuT/vXN6W8km+p90kWvuAOC5wcemZxVx6FD8a02zH/OjXPcpibCAkGAZ+u79zb6kPlrZO9MfLp6PVbzdDy0BuBfjex8qhFKDK33DboSF0TYDiFJmIShG3DJLzsugF2cnd0Yu0yYnMVmTGDKO4Szgi2iQGDoR2VpMm5TrXaL2t44tprQytKJVkI9XbUGMfcS53A+bURebcQzU7PA5UxgAYw=
  on:
    branch: master
  skip_existing: true
